server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    filters: stat,wall,log4j

logging:
  file: springboot.log
  level:
    org.mybatis: DEBUG
    org.mybatis.path: mybatis.log
    online.zhaopei.myproject.service: TRACE
    online.zhaopei.myproject.mapper: TRACE
    # org.springframework: DEBUG
